"""Field-level AST and round-trip tests for the reviewed 8.4 semantic examples.

The source snippets and the exclusion records are repository-owned copies of
the visually reviewed OMG Language PDF pages 435--440 (printed pages
403--408).  The expected AST values below are authored directly from the
grammar-facing dataclasses; they are deliberately not generated by parsing a
fixture, so a parser regression cannot silently regenerate its own oracle.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Tuple

import pytest

from pysysmlv2 import parse
from pysysmlv2.syntax.ast import (
    AttributeDefinition,
    AttributeUsage,
    Definition,
    DefinitionBody,
    DefinitionBodyItem,
    DefinitionDeclaration,
    DefinitionPrefix,
    DottedQualifiedReference,
    EventOccurrenceUsage,
    FeatureSpecialization,
    FeatureSpecializationPart,
    Identification,
    ItemDefinition,
    ItemUsage,
    Model,
    OccurrenceDefinition,
    OccurrenceDefinitionPrefix,
    OccurrenceUsage,
    OccurrenceUsagePrefix,
    OwnedFeatureTyping,
    PackageMember,
    QualifiedReference,
    ReferenceUsage,
    SubclassificationPart,
    Usage,
    UsageDeclaration,
    UsagePrefix,
)

pytestmark = pytest.mark.unit


ROOT = Path(__file__).resolve().parents[2]
FIXTURE_ROOT = ROOT / "test" / "testfile" / "omg_sysml2_language" / "manual"
LEDGER_PATH = ROOT / "docs" / "research" / "manual_pdf_review" / "section_8_4_3_8_4_6.json"


def _ledger() -> Dict[str, Any]:
    """Load the locally reviewed 8.4 ledger."""
    payload = json.loads(LEDGER_PATH.read_text(encoding="utf-8"))
    assert payload["scope"]["physical_pages"] == [435, 440]
    assert payload["scope"]["printed_pages"] == [403, 408]
    return payload


LEDGER = _ledger()
ENTRIES: Tuple[Dict[str, Any], ...] = tuple(LEDGER["entries"])
EXCLUSIONS: Tuple[Dict[str, Any], ...] = tuple(LEDGER["excluded_fragments"])


def _q(*segments: str) -> QualifiedReference:
    """Build one explicitly segmented qualified reference."""
    return QualifiedReference(list(segments))


def _dotted(*segments: str) -> DottedQualifiedReference:
    """Build a dotted-qualified reference whose final segment is qualified."""
    return DottedQualifiedReference([_q(*segments)])


def _specialization(operator: str, reference: Any) -> FeatureSpecialization:
    """Build one concrete feature-specialization field."""
    return FeatureSpecialization(operator, [reference])


def _subclassification(*segments: str) -> SubclassificationPart:
    """Build the explicit ``specializes`` field used by a definition."""
    return SubclassificationPart("specializes", [_q(*segments)])


def _definition(name: str, *segments: str, body: DefinitionBody) -> Definition:
    """Build a named definition with its explicit specialization and body."""
    return Definition(
        declaration=DefinitionDeclaration(
            identification=Identification(declared_name=name),
            subclassification=_subclassification(*segments),
        ),
        body=body,
    )


def _attribute_usage(
    name: str,
    *,
    reference: bool,
    specializations: Iterable[FeatureSpecialization],
    body: Optional[DefinitionBody] = None,
) -> AttributeUsage:
    """Build one attribute usage from its grammar-level fields."""
    return AttributeUsage(
        usage_prefix=UsagePrefix(is_reference=reference),
        usage=Usage(
            body=body if body is not None else DefinitionBody(declaration_only=True),
            declaration=UsageDeclaration(
                identification=Identification(declared_name=name),
                specialization=FeatureSpecializationPart(list(specializations)),
            ),
        ),
    )


def _expected_d1() -> Model:
    """Return the hand-authored AST expectation for the D1 example."""
    return Model(
        members=[
            PackageMember(
                element=AttributeDefinition(
                    definition_prefix=DefinitionPrefix(),
                    definition=_definition(
                        "D1",
                        "Base",
                        "DataValue",
                        body=DefinitionBody(
                            items=[
                                DefinitionBodyItem(
                                    element=ReferenceUsage(
                                        usage_prefix=UsagePrefix(),
                                        usage=Usage(
                                            body=DefinitionBody(declaration_only=True),
                                            declaration=UsageDeclaration(
                                                identification=Identification(declared_name="a"),
                                                specialization=FeatureSpecializationPart(
                                                    [
                                                        _specialization(
                                                            "subsets", _q("Base", "things")
                                                        )
                                                    ]
                                                ),
                                            ),
                                        ),
                                        has_ref_keyword=True,
                                    )
                                )
                            ]
                        ),
                    ),
                )
            )
        ]
    )


def _expected_d2_and_d() -> Model:
    """Return the hand-authored AST expectation for the D2/d panel."""
    d2_attribute = _attribute_usage(
        "a",
        reference=True,
        specializations=[
            _specialization(":", OwnedFeatureTyping(_dotted("ScalarValue", "String"))),
            _specialization("subsets", _q("Base", "dataValues")),
        ],
    )
    d_usage = _attribute_usage(
        "d",
        reference=True,
        specializations=[
            _specialization(":", OwnedFeatureTyping(_dotted("D2"))),
            _specialization("subsets", _q("Base", "dataValues")),
        ],
        body=DefinitionBody(
            items=[
                DefinitionBodyItem(
                    element=_attribute_usage(
                        "b",
                        reference=True,
                        specializations=[_specialization("subsets", _q("a"))],
                    )
                )
            ]
        ),
    )
    return Model(
        members=[
            PackageMember(
                element=AttributeDefinition(
                    definition_prefix=DefinitionPrefix(),
                    definition=_definition(
                        "D2",
                        "Base",
                        "DataValue",
                        body=DefinitionBody(items=[DefinitionBodyItem(element=d2_attribute)]),
                    ),
                )
            ),
            PackageMember(element=d_usage),
        ]
    )


def _expected_ind() -> Model:
    """Return the direct AST expectation for the individual-definition fixture."""
    return Model(
        members=[
            PackageMember(
                element=OccurrenceDefinition(
                    occurrence_definition_prefix=OccurrenceDefinitionPrefix(is_individual=True),
                    definition=Definition(
                        declaration=DefinitionDeclaration(
                            identification=Identification(declared_name="Ind")
                        ),
                        body=DefinitionBody(declaration_only=True),
                    ),
                )
            )
        ]
    )


def _occurrence_usage(
    name: str,
    *,
    prefix: Optional[OccurrenceUsagePrefix] = None,
    specialization: Optional[FeatureSpecializationPart] = None,
    body: Optional[DefinitionBody] = None,
) -> OccurrenceUsage:
    """Build one typed occurrence usage with its explicit grammar fields."""
    return OccurrenceUsage(
        occurrence_usage_prefix=prefix or OccurrenceUsagePrefix(),
        usage=Usage(
            body=body if body is not None else DefinitionBody(declaration_only=True),
            declaration=UsageDeclaration(
                identification=Identification(declared_name=name),
                specialization=specialization,
            ),
        ),
    )


def _occurrence_definition(
    name: str,
    *,
    specialization: Optional[SubclassificationPart] = None,
    body: Optional[DefinitionBody] = None,
) -> OccurrenceDefinition:
    """Build one typed occurrence definition from its explicit fields."""
    return OccurrenceDefinition(
        occurrence_definition_prefix=OccurrenceDefinitionPrefix(),
        definition=Definition(
            declaration=DefinitionDeclaration(
                identification=Identification(declared_name=name),
                subclassification=specialization,
            ),
            body=body if body is not None else DefinitionBody(declaration_only=True),
        ),
    )


def _expected_occurrence_members() -> Model:
    """Return the direct AST expectation for the occurrence-members fixture."""
    return Model(
        members=[
            PackageMember(
                element=_occurrence_definition(
                    "Occ",
                    specialization=_subclassification("Occurrences", "Occurrence"),
                    body=DefinitionBody(
                        items=[
                            DefinitionBodyItem(
                                element=_occurrence_usage(
                                    "a",
                                    prefix=OccurrenceUsagePrefix(is_reference=True),
                                    specialization=FeatureSpecializationPart(
                                        [
                                            _specialization(
                                                "subsets", _q("Occurrences", "occurrences")
                                            )
                                        ]
                                    ),
                                )
                            ),
                            DefinitionBodyItem(
                                element=_occurrence_usage(
                                    "b",
                                    specialization=FeatureSpecializationPart(
                                        [
                                            _specialization(
                                                "subsets",
                                                _q("Occurrences", "Occurrence", "suboccurrences"),
                                            )
                                        ]
                                    ),
                                )
                            ),
                        ]
                    ),
                )
            )
        ]
    )


def _expected_occurrence_portions() -> Model:
    """Return the direct AST expectation for the timeslice/snapshot fixture."""
    return Model(
        members=[
            PackageMember(
                element=_occurrence_definition(
                    "Occ",
                    body=DefinitionBody(
                        items=[
                            DefinitionBodyItem(
                                element=_occurrence_usage(
                                    "t",
                                    prefix=OccurrenceUsagePrefix(portion_kind="timeslice"),
                                )
                            ),
                            DefinitionBodyItem(
                                element=_occurrence_usage(
                                    "s",
                                    prefix=OccurrenceUsagePrefix(portion_kind="snapshot"),
                                )
                            ),
                        ]
                    ),
                )
            )
        ]
    )


def _expected_events() -> Model:
    """Return the direct AST expectation for the event-occurrence fixture."""
    event = EventOccurrenceUsage(
        occurrence_usage_prefix=OccurrenceUsagePrefix(),
        usage=Usage(body=DefinitionBody(declaration_only=True)),
        occurrence=True,
        usage_declaration=UsageDeclaration(
            identification=Identification(declared_name="evt"),
            specialization=FeatureSpecializationPart([_specialization("references", _q("occ1"))]),
        ),
    )
    return Model(
        members=[
            PackageMember(element=_occurrence_usage("occ1")),
            PackageMember(
                element=_occurrence_usage(
                    "occ2",
                    body=DefinitionBody(items=[DefinitionBodyItem(element=event)]),
                )
            ),
        ]
    )


def _expected_event_equivalent() -> Model:
    """Return the direct AST expectation for the event equivalent fixture."""
    return Model(
        members=[
            PackageMember(
                element=_occurrence_usage(
                    "occ1",
                    specialization=FeatureSpecializationPart(
                        [_specialization("subsets", _q("Occurrences", "occurrences"))]
                    ),
                )
            ),
            PackageMember(
                element=_occurrence_usage(
                    "occ2",
                    specialization=FeatureSpecializationPart(
                        [_specialization("subsets", _q("Occurrences", "occurrences"))]
                    ),
                    body=DefinitionBody(
                        items=[
                            DefinitionBodyItem(
                                element=_occurrence_usage(
                                    "evt",
                                    prefix=OccurrenceUsagePrefix(is_reference=True),
                                    specialization=FeatureSpecializationPart(
                                        [
                                            _specialization("references", _q("occ1")),
                                            _specialization(
                                                "subsets",
                                                _q(
                                                    "Occurrences",
                                                    "Occurrence",
                                                    "timeEnclosedOccurrences",
                                                ),
                                            ),
                                        ]
                                    ),
                                )
                            )
                        ]
                    ),
                )
            ),
        ]
    )


def _expected_item() -> Model:
    """Return the hand-authored AST expectation for the item example."""
    item_a = ItemUsage(
        occurrence_usage_prefix=OccurrenceUsagePrefix(is_reference=True),
        usage=Usage(
            body=DefinitionBody(declaration_only=True),
            declaration=UsageDeclaration(
                identification=Identification(declared_name="a"),
                specialization=FeatureSpecializationPart(
                    [_specialization("subsets", _q("Items", "items"))]
                ),
            ),
        ),
    )
    item_b = ItemUsage(
        occurrence_usage_prefix=OccurrenceUsagePrefix(),
        usage=Usage(
            body=DefinitionBody(declaration_only=True),
            declaration=UsageDeclaration(
                identification=Identification(declared_name="b"),
                specialization=FeatureSpecializationPart(
                    [_specialization("subsets", _q("Items", "Item", "subitems"))]
                ),
            ),
        ),
    )
    return Model(
        members=[
            PackageMember(
                element=ItemDefinition(
                    occurrence_definition_prefix=OccurrenceDefinitionPrefix(),
                    definition=_definition(
                        "I",
                        "Items",
                        "Item",
                        body=DefinitionBody(
                            items=[
                                DefinitionBodyItem(element=item_a),
                                DefinitionBodyItem(element=item_b),
                            ]
                        ),
                    ),
                )
            )
        ]
    )


EXPECTED = {
    "s843_p404_e01_d1.sysml": _expected_d1,
    "s843_p404_e02_d2_and_d.sysml": _expected_d2_and_d,
    "s845_p405_e01_ind.sysml": _expected_ind,
    "s845_p406_e02_occurrence_members.sysml": _expected_occurrence_members,
    "s845_p406_p407_e03_occurrence_portions.sysml": _expected_occurrence_portions,
    "s845_p407_e04_event_occurrences.sysml": _expected_events,
    "s845_p407_e05_event_occurrences_equivalent.sysml": _expected_event_equivalent,
    "s846_p408_e01_item_i.sysml": _expected_item,
}


def _ids(entries: Iterable[Dict[str, Any]]) -> Tuple[str, ...]:
    """Return stable IDs for parametrized source assertions."""
    return tuple("{}: {}".format(entry["id"], entry["fixture_name"]) for entry in entries)


@pytest.mark.parametrize("entry", ENTRIES, ids=_ids(ENTRIES))
def test_fixture_source_is_exactly_the_reviewed_pdf_panel(entry: Dict[str, Any]):
    """Ensure each local fixture remains byte-for-byte tied to the ledger."""
    path = FIXTURE_ROOT / entry["fixture_name"]
    assert path.is_file()
    assert path.read_text(encoding="utf-8") == entry["source_code"] + "\n"


def test_ledger_has_exactly_eight_complete_sysml_blocks_and_eight_exclusions():
    """Make the visual audit boundary explicit and keep KerML out of fixtures."""
    assert len(ENTRIES) == 8
    assert len(EXCLUSIONS) == 8
    assert all(entry["fixture_eligible"] is True for entry in ENTRIES)
    assert all(entry["fixture_eligible"] is False for entry in EXCLUSIONS)
    assert all("fixture_name" in entry for entry in ENTRIES)
    assert all("fixture_name" not in entry for entry in EXCLUSIONS)
    assert all(
        ("KerML" in entry["source_code"] or "..." in entry["source_code"]) for entry in EXCLUSIONS
    )


@pytest.mark.parametrize("entry", ENTRIES, ids=_ids(ENTRIES))
def test_fixture_has_independent_field_level_ast_and_roundtrip(entry: Dict[str, Any]):
    """Compare every AST dataclass field, then require canonical reparsing."""
    path = FIXTURE_ROOT / entry["fixture_name"]
    result = parse(path.read_text(encoding="utf-8"), str(path))
    assert result.ok, result.diagnostics
    expected_factory = EXPECTED[entry["fixture_name"]]
    expected = expected_factory()
    assert result.ast == expected

    exported = str(result.ast)
    reparsed = parse(exported, "roundtrip/{}".format(path.name))
    assert reparsed.ok, reparsed.diagnostics
    assert reparsed.ast == expected
    assert str(reparsed.ast) == exported
