"""Verify that checked-in generated ANTLR artifacts are reproducible.

The check reruns the normal submodule-copy and ANTLR build sequence, compares
all generated bytes before and after regeneration, and validates the manifest
and repository ownership contracts. It is safe to run before the first commit
because it compares snapshots instead of relying only on ``git diff``.

.. list-table:: Generated-artifact roadmap
   :header-rows: 1

   * - Symbol
     - Responsibility
   * - :func:`check`
     - Run regeneration and fail on drift or ownership violations.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "pysysmlv2" / "syntax" / "generated"

GENERATED_FILES = frozenset(
    {
        "SysMLv2Lexer.g4",
        "SysMLv2Lexer.interp",
        "SysMLv2Lexer.py",
        "SysMLv2Lexer.tokens",
        "SysMLv2Parser.g4",
        "SysMLv2Parser.interp",
        "SysMLv2Parser.py",
        "SysMLv2Parser.tokens",
        "SysMLv2ParserListener.py",
        "__init__.py",
        "manifest.json",
    }
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _check_agents_link() -> None:
    """Require the repository guidance link to resolve to ``CLAUDE.md``."""
    agents = ROOT / "AGENTS.md"
    claude = ROOT / "CLAUDE.md"
    if not claude.is_file():
        raise SystemExit("CLAUDE.md is missing")
    if not agents.is_symlink():
        raise SystemExit("AGENTS.md must be a symlink to CLAUDE.md")
    try:
        target = agents.resolve()
    except OSError as error:
        raise SystemExit("AGENTS.md cannot be resolved") from error
    if target != claude.resolve():
        raise SystemExit("AGENTS.md must be a symlink to CLAUDE.md")


def _check_generated_files() -> None:
    """Require every generated artifact to exist and contain data."""
    if not GENERATED.is_dir():
        raise SystemExit("generated ANTLR directory is missing")
    unexpected = sorted(
        path.name
        for path in GENERATED.iterdir()
        if path.is_file() and path.name not in GENERATED_FILES
    )
    if unexpected:
        raise SystemExit("unexpected generated ANTLR files: " + ", ".join(unexpected))
    missing = sorted(name for name in GENERATED_FILES if not (GENERATED / name).is_file())
    if missing:
        raise SystemExit("generated ANTLR files are missing: " + ", ".join(missing))
    empty = sorted(name for name in GENERATED_FILES if (GENERATED / name).stat().st_size == 0)
    if empty:
        raise SystemExit("generated ANTLR files are empty: " + ", ".join(empty))


def _check_manifest() -> None:
    """Validate manifest metadata and hashes against checked-in grammar inputs."""
    path = GENERATED / "manifest.json"
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise SystemExit("generated manifest is missing or invalid") from error
    if not isinstance(manifest, dict):
        raise SystemExit("generated manifest must be a JSON object")

    required = {
        "antlr_jar_sha256",
        "antlr_version",
        "grammar_version",
        "omg_release",
        "source_commit",
        "source_grammar_sha256",
        "source_repository",
        "source_tag",
    }
    missing = sorted(required.difference(manifest))
    if missing:
        raise SystemExit("generated manifest fields are missing: " + ", ".join(missing))

    for name in sorted(required - {"source_grammar_sha256"}):
        value = manifest[name]
        if not isinstance(value, str) or not value:
            raise SystemExit("generated manifest field is invalid: " + name)
    hashes = manifest["source_grammar_sha256"]
    if not isinstance(hashes, dict):
        raise SystemExit("generated manifest source_grammar_sha256 must be an object")
    expected = {
        "lexer": _sha256(GENERATED / "SysMLv2Lexer.g4"),
        "parser": _sha256(GENERATED / "SysMLv2Parser.g4"),
    }
    if hashes != expected:
        raise SystemExit("generated manifest grammar hashes do not match generated G4 files")


def _snapshot() -> dict:
    """Return byte snapshots for files in the generated directory.

    :return: Mapping from generated relative names to file bytes.
    :rtype: dict[str, bytes]
    """
    if not GENERATED.is_dir():
        return {}
    return {path.name: path.read_bytes() for path in GENERATED.iterdir() if path.is_file()}


def _has_commit() -> bool:
    """Return whether the repository has a commit for tracked-file checks.

    :return: ``True`` when ``HEAD`` resolves to a commit.
    :rtype: bool
    """
    try:
        subprocess.check_call(
            ["git", "rev-parse", "--verify", "HEAD"],
            cwd=str(ROOT),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return False
    return True


def _check_tracked_files() -> None:
    """Require generated files to be tracked after the initial commit.

    :return: ``None`` when no tracked-file violation exists.
    :rtype: None
    :raises SystemExit: If a committed repository omits a generated artifact.
    """
    if not _has_commit():
        return
    try:
        tracked = subprocess.check_output(
            ["git", "ls-files", "--", "pysysmlv2/syntax/generated"],
            cwd=str(ROOT),
            text=True,
        ).splitlines()
    except (OSError, subprocess.CalledProcessError) as error:
        raise SystemExit("cannot inspect tracked generated ANTLR files") from error
    expected = {"pysysmlv2/syntax/generated/" + name for name in GENERATED_FILES}
    missing = sorted(expected.difference(tracked))
    if missing:
        raise SystemExit("generated ANTLR files are not tracked: " + ", ".join(missing))


def check() -> None:
    """Regenerate grammar artifacts and fail when bytes or contracts change.

    :return: ``None`` when regeneration is reproducible.
    :rtype: None
    :raises SystemExit: If generated files drift or repository contracts fail.

    Example::

        $ make antlr_check
    """
    _check_agents_link()
    before = _snapshot()
    subprocess.check_call([os.environ.get("MAKE", "make"), "antlr_update"], cwd=str(ROOT))
    _check_generated_files()
    _check_manifest()
    after = _snapshot()
    if before != after:
        raise SystemExit("generated ANTLR artifacts are not reproducible")
    _check_tracked_files()


if __name__ == "__main__":  # pragma: no cover
    check()
