"""Verify that checked-in generated ANTLR artifacts are reproducible.

The check reruns the normal submodule-copy and ANTLR build sequence, compares
all generated bytes before and after regeneration, and validates repository
ownership contracts. It is safe to run before the first commit because it
compares snapshots instead of relying only on ``git diff``.

.. list-table:: Generated-artifact roadmap
   :header-rows: 1

   * - Symbol
     - Responsibility
   * - :func:`check`
     - Run regeneration and fail on drift or ownership violations.
"""

from __future__ import annotations

import json
import os
import subprocess
from hashlib import sha256
from pathlib import Path

from tools.grammar_overlay import OVERLAY_IDENTIFIER

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "pysysmlv2" / "syntax" / "generated"
UPSTREAM_LICENSE = ROOT / "upstream" / "sysml-v2-grammar" / "LICENSE"

GENERATED_FILES = frozenset(
    {
        "SysMLv2Lexer.g4",
        "SysMLv2Lexer.interp",
        "SysMLv2Lexer.py",
        "SysMLv2Lexer.tokens",
        "SysMLv2Parser.g4",
        "SysMLv2Parser.interp",
        "SysMLv2Parser.py",
        "SysMLv2Parser.tokens",
        "SysMLv2ParserListener.py",
        "UPSTREAM_LICENSE.txt",
        "__init__.py",
        "grammar-provenance.json",
    }
)


def _check_agents_link() -> None:
    """Require the repository guidance link to resolve to ``CLAUDE.md``."""
    agents = ROOT / "AGENTS.md"
    claude = ROOT / "CLAUDE.md"
    if not claude.is_file():
        raise SystemExit("CLAUDE.md is missing")
    if not agents.is_symlink():
        raise SystemExit("AGENTS.md must be a symlink to CLAUDE.md")
    try:
        target = agents.resolve()
    except OSError as error:
        raise SystemExit("AGENTS.md cannot be resolved") from error
    if target != claude.resolve():
        raise SystemExit("AGENTS.md must be a symlink to CLAUDE.md")


def _check_generated_files() -> None:
    """Require every generated artifact to exist and contain data."""
    if not GENERATED.is_dir():
        raise SystemExit("generated ANTLR directory is missing")
    unexpected = sorted(
        path.name
        for path in GENERATED.iterdir()
        if path.is_file() and path.name not in GENERATED_FILES
    )
    if unexpected:
        raise SystemExit("unexpected generated ANTLR files: " + ", ".join(unexpected))
    missing = sorted(name for name in GENERATED_FILES if not (GENERATED / name).is_file())
    if missing:
        raise SystemExit("generated ANTLR files are missing: " + ", ".join(missing))
    empty = sorted(name for name in GENERATED_FILES if (GENERATED / name).stat().st_size == 0)
    if empty:
        raise SystemExit("generated ANTLR files are empty: " + ", ".join(empty))


def _check_grammar_provenance() -> None:
    """Require a valid manifest for the copied grammar and local overlay.

    :return: ``None`` when the manifest has the expected effective hash.
    :rtype: None
    :raises SystemExit: If provenance data is missing, malformed, or stale.
    """
    manifest_path = GENERATED / "grammar-provenance.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise SystemExit("generated grammar provenance is unreadable") from error
    expected_hash = sha256((GENERATED / "SysMLv2Parser.g4").read_bytes()).hexdigest()
    if manifest.get("schema_version") != 1:
        raise SystemExit("generated grammar provenance schema is unsupported")
    if manifest.get("overlay") != OVERLAY_IDENTIFIER:
        raise SystemExit("generated grammar provenance has an unknown overlay")
    upstream = manifest.get("upstream")
    if not isinstance(upstream, dict) or not all(
        isinstance(upstream.get(key), str) and upstream[key]
        for key in ("revision", "describe", "parser_sha256")
    ):
        raise SystemExit("generated grammar provenance lacks upstream revision data")
    if manifest.get("effective_parser_sha256") != expected_hash:
        raise SystemExit("generated grammar provenance hash does not match parser grammar")


def _check_upstream_license() -> None:
    """Require the packaged grammar license to match the pinned submodule.

    :return: ``None`` when the generated license copy is byte-for-byte current.
    :rtype: None
    :raises SystemExit: If the upstream license or generated copy is missing or
        differs.
    """
    packaged = GENERATED / "UPSTREAM_LICENSE.txt"
    if not UPSTREAM_LICENSE.is_file():
        raise SystemExit("upstream grammar license is missing")
    if not packaged.is_file():
        raise SystemExit("generated upstream grammar license is missing")
    if packaged.read_bytes() != UPSTREAM_LICENSE.read_bytes():
        raise SystemExit("generated upstream grammar license is stale")


def _snapshot() -> dict:
    """Return byte snapshots for files in the generated directory.

    :return: Mapping from generated relative names to file bytes.
    :rtype: dict[str, bytes]
    """
    if not GENERATED.is_dir():
        return {}
    return {path.name: path.read_bytes() for path in GENERATED.iterdir() if path.is_file()}


def _has_commit() -> bool:
    """Return whether the repository has a commit for tracked-file checks.

    :return: ``True`` when ``HEAD`` resolves to a commit.
    :rtype: bool
    """
    try:
        subprocess.check_call(
            ["git", "rev-parse", "--verify", "HEAD"],
            cwd=str(ROOT),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return False
    return True


def _check_tracked_files() -> None:
    """Require generated files to be tracked after the initial commit.

    :return: ``None`` when no tracked-file violation exists.
    :rtype: None
    :raises SystemExit: If a committed repository omits a generated artifact.
    """
    if not _has_commit():
        return
    try:
        tracked = subprocess.check_output(
            ["git", "ls-files", "--", "pysysmlv2/syntax/generated"],
            cwd=str(ROOT),
            text=True,
        ).splitlines()
    except (OSError, subprocess.CalledProcessError) as error:
        raise SystemExit("cannot inspect tracked generated ANTLR files") from error
    expected = {"pysysmlv2/syntax/generated/" + name for name in GENERATED_FILES}
    missing = sorted(expected.difference(tracked))
    if missing:
        raise SystemExit("generated ANTLR files are not tracked: " + ", ".join(missing))


def check() -> None:
    """Regenerate grammar artifacts and fail when bytes or contracts change.

    :return: ``None`` when regeneration is reproducible.
    :rtype: None
    :raises SystemExit: If generated files drift or repository contracts fail.

    Example::

        $ make antlr_check
    """
    _check_agents_link()
    before = _snapshot()
    subprocess.check_call([os.environ.get("MAKE", "make"), "antlr_update"], cwd=str(ROOT))
    _check_generated_files()
    _check_grammar_provenance()
    _check_upstream_license()
    after = _snapshot()
    if before != after:
        raise SystemExit("generated ANTLR artifacts are not reproducible")
    _check_tracked_files()


if __name__ == "__main__":  # pragma: no cover
    check()
